variables:
  DOCKER_BUILDER_IMAGE: ${CI_REGISTRY_IMAGE}/docker-builder:latest

stages:
  - pre-build
  - build
  - pre-test
  - test

.docker-login-before-script: &docker-login-before-script
  before_script:
    - docker login -u "${CI_REGISTRY_USER?}" -p "${CI_REGISTRY_PASSWORD?} "${CI_REGISTRY?}"

.docker-build-tmpl: &docker-build-tmpl
  << : *docker-login-before-script
  stage: build
  image: $DOCKER_BUILDER_IMAGE
  services:
    - docker:dind
  script:
    - git fetch --tags
    - VERSION="$(git describe --tags --always)"
    - VERSION="${VERSION%-*-*}"
    - RELEASE=$(jq -r .release < etc/ncp.cfg)
    - '[[ "${ARCHITECTURE?}" == "x86"   ]] && { ARCH=amd64; ARCH_QEMU=x86_64; NCP_TAG=x86; }'
    - '[[ "${ARCHITECTURE?}" == "armhf"   ]] && { ARCH=arm32v7; ARCH_QEMU=arm; NCP_TAG=armhf; }'
    - '[[ "${ARCHITECTURE?}" == "arm64"   ]] && { ARCH=arm64v8; ARCH_QEMU=aarch64; NCP_TAG=arm64; }'
    - docker pull ${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:latest || true
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/debian-ncp/Dockerfile --pull
      --build-arg release=${RELEASE?} --build-arg arch=${ARCH?} --build-arg arch_qemu=${ARCH_QEMU?}
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/lamp/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?}
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/nextcloud/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?}
      -t "${CI_REGISTRY_IMAGE?}/nextcloud-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/nextcloud-${NCP_TAG}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE}/nextcloud-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/nextcloudpi/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?} --build-arg ncp_ver=${VERSION?}
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:${VERSION?}"
    - docker push ${CI_REGISTRY_IMAGE}/debian-ncp-${NCP_TAG?}
    - docker push ${CI_REGISTRY_IMAGE}/lamp-${NCP_TAG?}
    - docker push ${CI_REGISTRY_IMAGE}/nextcloud-${NCP_TAG?}
    - docker push ${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}

.integration-tests-docker-tmpl: &integration-tests-docker-tmpl
  stage: test
  services:
    - name: selenium/standalone-firefox
      alias: selenium
    - name: "${CI_REGISTRY_IMAGE}/ncp-testing-${ARCHITECTURE}:${CI_PIPELINE_IID}"
      alias: nextcloudpi
  image: python:3.8-buster
  script:
    - pip install selenium
    - NCP_IP="$(getent hosts nextcloudpi | cut -f1 -d ' ')"
    - ./tests/activation_tests.py "$NCP_IP" "http://selenium:4444/wd/hub"
    - ./tests/nextcloud_tests.py "$NCP_IP" "http://selenium:4444/wd/hub"

.system-test-docker-tmpl: &system-test-docker-tmpl
  stage: pre-build
  image: "${CI_REGISTRY_IMAGE}/nextcloudpi-${ARCHITECTURE}:${CI_PIPELINE_IID}"
  script:
    - ./tests/sysyem_tests.py

.build-test-image-tmpl: &build-test-image-tmpl
  <<: *docker-login-before-script
  stage: pre-test
  image: $DOCKER_BUILDER_IMAGE
  services:
    - docker:dind
  script:
    - '[[ "${ARCHITECTURE?}" == "armhf" ]] && QEMU_ARCH="arm"     || true'
    - '[[ "${ARCHITECTURE?}" == "arm64" ]] && QEMU_ARCH="aarch64" || true'
    - |
      docker build --progress=plain . -f - -t "${CI_REGISTRY_IMAGE}/ncp-testing-${ARCHITECTURE?}:${CI_PIPELINE_IID}" <<-EOF
        FROM ${CI_REGISTRY_IMAGE}/nextcloudpi-${ARCHITECTURE?}:${CI_PIPELINE_IID}";
        COPY qemu-${QEMU_ARCH?}-static /usr/bin
      EOF
    - docker push "${CI_REGISTRY_IMAGE}/ncp-testing-${ARCHITECTURE?}";

test-docker-x86:
  << : *integration-tests-docker-tmpl
  variables:
    ARCHITECTURE: "x86"
    NAME: nextcloudpi

test-docker-armhf:
  << : *integration-tests-docker-tmpl
  variables:
    ARCHITECTURE: "armhf"
    NAME: nextcloudpi

test-docker-arm64:
  << : *integration-tests-docker-tmpl
  variables:
    ARCHITECTURE: "arm64"
    NAME: nextcloudpi

#system-tests-docker-amd64:
#  << : *system-test-docker-tmpl
#  variables:
#    ARCHITECTURE: "x86"

docker-build-amd64:
  << : *docker-build-tmpl
  variables:
    ARCHITECTURE: "x86"

docker-build-armhf:
  <<: *docker-build-tmpl
  variables:
    ARCHITECTURE: "armhf"

docker-build-arm64:
  <<: *docker-build-tmpl
  variables:
    ARCHITECTURE: "arm64"

build-docker-builder:
  << : *docker-login-before-script
  stage: pre-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/docker-builder:latest || echo "docker-builder:latest not found in \"${CI_REGISTRY_IMAGE}\"!"
    - CURRENT="$(docker inspect -f '{{ .DockerVersion }}' ${CI_REGISTRY_IMAGE}/docker-builder:latest || echo "NONE")"
    - LATEST="$(docker version -f '{{ .Client.Version }}')"
    - echo "$CURRENT"
    - echo "$LATEST"
    - |
      if [[ "$CURRENT" != "$LATEST" ]]
      then
        docker build --progress=plain . -f ci/docker/docker-builder/Dockerfile -t "${CI_REGISTRY_IMAGE}/docker-builder:latest"
        docker push "${CI_REGISTRY_IMAGE}/docker-builder:latest"
      fi

build-arm64-test-image:
  << : *build-test-image-tmpl
  variables:
    ARCHITECTURE: arm64

build-armhf-test-image:
  << : *build-test-image-tmpl
  variables:
    ARCHITECTURE: armhf

tag-amd64-test-image:
  << : *docker-login-before-script
  stage: pre-test
  image: $DOCKER_BUILDER_IMAGE
  services:
    - docker:dind
  script:
    - docker tag "${CI_REGISTRY_IMAGE}/nextcloudpi-amd64:${CI_PIPELINE_IID}" "${CI_REGISTRY_IMAGE}/ncp-testing-amd64:${CI_PIPELINE_IID}"
    - docker push "${CI_REGISTRY_IMAGE}/ncp-testing-amd64";
